#!/usr/bin/env python

import sys
import os
import string

def help():
    print """
    [DVI -> PDF] May 2001 (C) J Candy
    
    Usage:

     dvpdf <file>.dvi    
     
    Output:

     <file>.pdf
    """
    
if len(sys.argv) == 1:
    help()
else:
    print "Modified dvips acting on "+sys.argv[1]
    os.system("dvips -t letter -Ppdf -G0 -o /tmp/a.ps "+sys.argv[1])
    file = string.splitfields(sys.argv[1],'.')
    base = file[0]
    os.system("ps2pdf -sPAPERSIZE=letter \
    -dMaxSubsetPct=100 -dCompatibilityLevel=1.3 \
    -dSubsetFonts=true -dEmbedAllFonts=true \
    -dAutoFilterColorImages=false \
    -dAutoFilterGrayImages=false \
    -dColorImageFilter=/FlateEncode \
    -dGrayImageFilter=/FlateEncode \
    -dMonoImageFilter=/FlateEncode \
    /tmp/a.ps "+base+".pdf")
    os.system("rm /tmp/a.ps")
