iaeapaper:	
	pdflatex iaeapaper-example
	bibtex iaeapaper-example
	pdflatex iaeapaper-example ; pdflatex iaeapaper-example

clean:
	rm -f iaeapaper-example.pdf
	rm -f *dvi *idx *log *toc *bbl *aux *blg *out
